version: "2"

services:
  kumuluz:
    image: yoksar/authentication-service
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/authentication
      DATABASE_USER: postgres
      DATABASE_PASS: postgres
      JWT_SECRET: secret
    ports:
      - 8080:8080

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authentication
    ports:
      - 5432:5432

networks:
    default:
        driver: bridge